site_name: UbiHome
site_url: https://ubihome.github.io
edit_uri: edit/main/docs/
repo_url: https://github.com/UbiHome/ubihome.github.io
strict: true
extra:
  homepage: https://ubihome.github.io/
plugins:
  - search
  - social
  - offline
  - awesome-nav
  - macros
  - tags
  - git-revision-date-localized:
      enable_creation_date: true


theme:
  name: material
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes 
    - toc.follow
    - navigation.top
    - search
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate 
    - content.tabs.link
    - content.tooltips
    - content.footnote.tooltips
    - content.action.edit
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
      base_path:
        - "."
        - "docs"
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - admonition
  - abbr
  - attr_list
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
