ubihome:
  name: New Awesome UbiHome Device

api:

shell:

button:
  - platform: shell
    id: my_button
    name: 'Write Hello World'
    command: "echo 'Hello World!' >> test.log"

sensor:
  - platform: shell
    name: 'RAM Usage'
    id: ram_usage
    icon: mdi:memory
    state_class: 'measurement'
    unit_of_measurement: '%'
    update_interval: 30s
    command: |-
      Get-WmiObject Win32_OperatingSystem -Property * | % {([math]::Round(($_.FreePhysicalMemory)/$_.totalvisiblememorysize,2))}