ubihome:
  name: new_awesome

mqtt:
  broker: 192.168.178.167
  username: test
  password: a887aeda-7248-4b0f-a2e7-6f4ee0026f5e

shell:

button:
  - platform: shell
    id: my_button
    name: 'Write Hello World'
    command: "echo 'Hello World!' >> test.log"

sensor:
  - platform: shell
    name: "RAM Usage"
    id: ram_usage
    icon: mdi:memory
    state_class: "measurement"
    unit_of_measurement: "%"
    update_interval: 30s # 0 only executes it once and assumes a long running processes.
    command: |-
      free | grep Mem | awk '{print $3/$2 * 100.0}'