nav:
  - Home: index.md
  - Getting started: getting_started/index.md
  - Features: 
    - features/index.md
    - Connectivity:
      - features/connectivity/index.md
      - features/connectivity/*
    - Components:
      - features/components/index.md
      - features/components/*
    - Platforms:
      - features/platforms/index.md
      - features/platforms/*
  - Examples:
    - "examples/*"